// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// pack_name_posterior_cpp
List pack_name_posterior_cpp(CharacterVector names, List neighbor_list, NumericVector x_avg, NumericVector p_avg);
RcppExport SEXP _nicknamer_pack_name_posterior_cpp(SEXP namesSEXP, SEXP neighbor_listSEXP, SEXP x_avgSEXP, SEXP p_avgSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type names(namesSEXP);
    Rcpp::traits::input_parameter< List >::type neighbor_list(neighbor_listSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_avg(x_avgSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type p_avg(p_avgSEXP);
    rcpp_result_gen = Rcpp::wrap(pack_name_posterior_cpp(names, neighbor_list, x_avg, p_avg));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nicknamer_pack_name_posterior_cpp", (DL_FUNC) &_nicknamer_pack_name_posterior_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_nicknamer(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
