# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sampleZ_cpp <- function(n, p, delta, neighbor_list, dist_mat, lambda) {
    .Call('_nicknamer_sampleZ_cpp', PACKAGE = 'nicknamer', n, p, delta, neighbor_list, dist_mat, lambda)
}

sampleLambda_cpp <- function(d_off, z_off, lambda, lambda_rate) {
    .Call('_nicknamer_sampleLambda_cpp', PACKAGE = 'nicknamer', d_off, z_off, lambda, lambda_rate)
}

