# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_bayes_choice_dictionary_cpp <- function(names, D, p, delta, lambda) {
    .Call(`_nicknamer_make_bayes_choice_dictionary_cpp`, names, D, p, delta, lambda)
}

