# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pack_name_posterior_cpp <- function(names, neighbor_list, x_avg, p_avg) {
    .Call(`_nicknamer_pack_name_posterior_cpp`, names, neighbor_list, x_avg, p_avg)
}

sampleZ_cpp <- function(n, p, delta, neighbor_list, G_list) {
    .Call(`_nicknamer_sampleZ_cpp`, n, p, delta, neighbor_list, G_list)
}

